#!/bin/bash

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)

function name_to_creation_precise() {
	prefix=$(stat -c '%y' "$@" | tr ' ' '_' | tr -c '[:alnum:]._+-' '-')
	pretty=$(name_formatter "$@")
	newName="${prefix}_${pretty}"
	mv "$@" "$newName"
}

function main() {
	while read -r x; do
		name_to_creation_precise "$x"
	done
}

main
